// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hekxwoarwbjirpdesoyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhla3h3b2Fyd2JqaXJwZGVzb3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDM0MjYsImV4cCI6MjA2OTMxOTQyNn0.pYU5xfs5TNNrqiNwb-c-zVUpUPnQ1GxnsmF9xG5F77k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});